language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
env:
    - TOXENV=py36
    - TOXENV=py37
    - TOXENV=py38
    - TOXENV=pep8
    - TOXENV=coverage
matrix:
    include:
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.8"
          env: TOXENV=pep8
        - python: "3.8"
          env: TOXENV=coverage
install:
    - pip install tox
    - if [ "$TOXENV" = 'py38' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'py38' ]; then coveralls; fi
